{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "utils",
    "version": "4.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "uv2vt7q6hrejrkz5uuy5wb7fxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "pluginapi",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "utils-4.5.1.jar",
          "url": "utils-4.5.1.jar",
          "size": 65848,
          "sha512": "1a808625cf0710d3c9a20f9258c226fa9da3891dbb87e5e3d0ad456fcf13462a2582183c4135e6deb354ab79d4a9994768d730c8956532ef0b7bc31360ff82cf",
          "sha256": "611a5f48de2f5b7add2edfdb5986a499f21ddfadb5784bd157031b4c524bac8e",
          "sha1": "a5829ee6141cad1fdf18b86e13adfc16b0476d2b",
          "md5": "9c11e78cdc5d663c41928976dae907d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.0.1-jre"
          }
        },
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "pluginapi",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "utils-4.5.1.jar",
          "url": "utils-4.5.1.jar",
          "size": 65848,
          "sha512": "1a808625cf0710d3c9a20f9258c226fa9da3891dbb87e5e3d0ad456fcf13462a2582183c4135e6deb354ab79d4a9994768d730c8956532ef0b7bc31360ff82cf",
          "sha256": "611a5f48de2f5b7add2edfdb5986a499f21ddfadb5784bd157031b4c524bac8e",
          "sha1": "a5829ee6141cad1fdf18b86e13adfc16b0476d2b",
          "md5": "9c11e78cdc5d663c41928976dae907d4"
        }
      ]
    }
  ]
}
